version: '3.8'
services:
  cache:
    image: redis
    ports:
      - "6379:6379"
  api:
    build: .
    ports:
      - "80:3000"
    depends_on:
      - cache
    environment:
      - REDIS_URL=redis://cache:6379
    